name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run unit tests
        run: make test

      - name: Generate version
        run: echo "RELEASE_VERSION=$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_ENV

      - name: Create git tag
        run: |
          git config --local user.email "users@noreply.github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ env.RELEASE_VERSION }} -m "Release ${{ env.RELEASE_VERSION }}"
          git push origin ${{ env.RELEASE_VERSION }}

      - name: Release ${{ env.RELEASE_VERSION }}
        id: release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete git tag if release failed and exit
        if: failure()
        run: |
          git tag -d ${{ env.RELEASE_VERSION }}
          git push origin --delete ${{ env.RELEASE_VERSION }}
          exit 1

      - name: Add links to summary
        run: |
          echo "### Release ${{ env.RELEASE_VERSION }} completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "- [Release page](https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }})" >> $GITHUB_STEP_SUMMARY
